dashboards/urls.py
# -*- coding: utf-8 -*-

# Librerias Django:

# Urls
from django.conf.urls import url

# Vistas
from .views import Inicio

app_name = "dashboards"

urlpatterns = [

    url(
        r'^inicio/$',
        Inicio.as_view(),
        name='inicio'
    ),
]

home/urls.py
# -*- coding: utf-8 -*-

# Librerias django:
# from django.conf.urls import url

# Vistas:
# from .views import Index

# urlpatterns = [
#     url(r'^index/$', Index.as_view(), name='home.index'),
# ]

inventarios/urls.py
# -*- coding: utf-8 -*-

# Librerias Django:
from django.conf.urls import url

# Vistas:
from .views import AlmacenListView
from .views import AlmacenCreateView
from .views import AlmacenUpdateView

from .views import StockListView

from .views import UdmArticuloListView
from .views import UdmArticuloCreateView
from .views import UdmArticuloUpdateView

from .views import ArticuloListView
from .views import ArticuloCreateView
from .views import ArticuloUpdateView

from .views import ArticuloAnexoTextoView
from .views import ArticuloAnexoImagenView
from .views import ArticuloAnexoArchivoView

from .views import EntradaListView
from .views import EntradaCabeceraCreateView
from .views import EntradaCabeceraUpdateView
from .views import SalidaListView
from .views import SalidaCabeceraCreateView
from .views import SalidaCabeceraUpdateView
from .views import EntradaSaldoListView
from .views import EntradaSaldoCreateView
from .views import EntradaSaldoUpdateView
from .views import EntradaCompraListView
from .views import EntradaCompraCreateView
from .views import EntradaCompraUpdateView

app_name = "inventarios"

urlpatterns = [

    # ----------------- ALMACEN ----------------- #

    url(
        r'^almacenes/$',
        AlmacenListView.as_view(),
        name='almacenes_lista'
    ),
    url(
        r'^almacenes/nuevo/$',
        AlmacenCreateView.as_view(),
        name='almacenes_nuevo'
    ),
    url(
        r'^almacenes/editar/(?P<pk>.*)/$',
        AlmacenUpdateView.as_view(),
        name='almacenes_editar'
    ),


    # ----------------- UDM ARTICULO ----------------- #

    url(
        r'udmarticulo/$',
        UdmArticuloListView.as_view(),
        name='udms_articulo_lista'
    ),
    url(
        r'udmarticulo/nuevo/$',
        UdmArticuloCreateView.as_view(),
        name='udms_articulo_nuevo'
    ),
    url(
        r'udmarticulo/editar/(?P<pk>\d+)/$',
        UdmArticuloUpdateView.as_view(),
        name='udms_articulo_editar'
    ),



    # ----------------- ARTICULOS ----------------- #

    url(
        r'^articulos/$',
        ArticuloListView.as_view(),
        name='articulos_lista'
    ),
    url(
        r'^articulos/nuevo/$',
        ArticuloCreateView.as_view(),
        name='articulos_nuevo'
    ),
    url(
        r'^articulos/editar/(?P<pk>.*)/$',
        ArticuloUpdateView.as_view(),
        name='articulos_editar'
    ),


    # ----------------- ARTICULOS - ANEXOS ----------------- #

    url(
        r'articulos/anexos/(?P<pk>\d+)/texto/$',
        ArticuloAnexoTextoView.as_view(),
        name='anexar_texto'
    ),
    url(
        r'^articulos/anexos/(?P<pk>\d+)/imagen/$',
        ArticuloAnexoImagenView.as_view(),
        name='anexar_imagen'
    ),
    url(
        r'^articulos/anexos/(?P<pk>\d+)/archivo/$',
        ArticuloAnexoArchivoView.as_view(),
        name='anexar_archivo'
    ),


    # ----------------- STOCK ----------------- #

    url(
        r'^stock/(?P<almacen>\d+)/(?P<articulo>\d+)/$',
        StockListView.as_view(),
        name='stock'
    ),


    # ----------------- ENTRADAS ----------------- #

    url(
        r'entradas/$',
        EntradaListView.as_view(),
        name='entradas_lista'
    ),
    url(
        r'entradas/nuevo/$',
        EntradaCabeceraCreateView.as_view(),
        name='entradas_nuevo'
    ),
    url(
        r'entradas/editar/(?P<pk>\d+)/$',
        EntradaCabeceraUpdateView.as_view(),
        name='entradas_editar'
    ),
    url(
        r'entradas/saldo_inicial/$',
        EntradaSaldoListView.as_view(),
        name='entradas_saldoinicial_lista'
    ),
    url(
        r'entradas/saldo_inicial/nuevo/$',
        EntradaSaldoCreateView.as_view(),
        name='entradas_saldoinicial_nuevo'
    ),
    url(
        r'entradas/saldo_inicial/editar/(?P<pk>\d+)/$',
        EntradaSaldoUpdateView.as_view(),
        name='entradas_saldoinicial_editar'
    ),
    url(
        r'entradas/compras/$',
        EntradaCompraListView.as_view(),
        name='entradas_compras_lista'
    ),
    url(
        r'entradas/saldo_inicial/nuevo/$',
        EntradaCompraCreateView.as_view(),
        name='entradas_compras_nuevo'
    ),
    url(
        r'entradas/saldo_inicial/editar/(?P<pk>\d+)/$',
        EntradaCompraUpdateView.as_view(),
        name='entradas_compras_editar'
    ),
    # ----------------- SALIDAS ----------------- #
    url(
        r'salidas/$',
        SalidaListView.as_view(),
        name='salidas_lista'
    ),
    url(
        r'salidas/nuevo/$',
        SalidaCabeceraCreateView.as_view(),
        name='salidas_nuevo'
    ),
    url(
        r'salidas/editar/(?P<pk>\d+)/$',
        SalidaCabeceraUpdateView.as_view(),
        name='salidas_editar'
    ),
]

inventarios/models.py
# -*- coding: utf-8 -*-

# Librerias Django:
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Otros Modelos:
from seguridad.models import Empresa

# Validadores:
from home.validators import valid_extension
from home.validators import validate_image

# Historia
from simple_history.models import HistoricalRecords

ARTICULO_TIPO = (
    ('INS', 'INSUMO'),
    ('HER', 'HERRAMIENTA'),
    ('ACT', 'ACTIVO'),
    ('REF', 'REFACCION'),
)

ARTICULO_ESTADO = (
    ('ACT', 'ACTIVO'),
    ('DES', 'DESHABILITADO'),
)

ALMACEN_ESTADO = (
    ('ACT', 'ACTIVO'),
    ('DES', 'DESHABILITADO'),
)

MOVIMIENTO_ESTADO = (
    ('CAP', 'CAPTURA'),
    ('CER', 'CERRADO'),
)

MOVIMIENTO_TIPO = (
    ('ENT', 'ENTRADA'),
    ('SAL', 'SALIDA'),
)

MOVIMIENTO_CLASIFICACION = (
    ('SAL', 'SALDO INICIAL'),
    ('COM', 'COMPRA'),
    ('TRA', 'TRASPASO'),
    ('AJU', 'AJUSTE'),
    ('OT', 'ORDEN'),
    ('DES', 'DESPACHO A PERSONAL'),
)


class UdmArticulo(models.Model):
    clave = models.CharField(max_length=144, unique=True)
    descripcion = models.CharField(max_length=144, null=True)
    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
        null=True,
        blank=True
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
        null=True,
        blank=True
    )
    history = HistoricalRecords()

    def __str__(self):
        return "({}) {}".format(
            self.clave.encode('utf-8'),
            self.descripcion.encode('utf-8')
        )


class Articulo(models.Model):
    clave = models.CharField(max_length=144, null=True)
    descripcion = models.CharField(max_length=144, null=True)
    estado = models.CharField(
        max_length=4,
        choices=ARTICULO_ESTADO,
        default="ACT",
    )
    tipo = models.CharField(
        max_length=6,
        choices=ARTICULO_TIPO,
        default="CORRE",
        blank=True
    )
    imagen = models.ImageField(
        upload_to='articulos/img',
        blank=True,
        null=True,
        validators=[
            valid_extension,
            validate_image
        ]
    )
    udm = models.ForeignKey(
        UdmArticulo,
        on_delete=models.PROTECT
    )
    clave_jde = models.CharField(max_length=144, blank=True, null=True)
    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
        null=True,
        blank=True
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
        null=True,
        blank=True
    )
    history = HistoricalRecords()

    def __str__(self):
        return "({0}) {1}".format(
            self.clave,
            self.descripcion
        ).encode('utf-8')

    class Meta:
        verbose_name_plural = "Articulo"


class Almacen(models.Model):
    empresa = models.ForeignKey(
        Empresa, null=True,
        blank=True,
        on_delete=models.PROTECT
    )
    clave = models.CharField(max_length=144, null=True)
    descripcion = models.CharField(max_length=144, null=True)
    estado = models.CharField(
        max_length=4,
        choices=ALMACEN_ESTADO,
        default="ACT",
        blank=True
    )
    articulos = models.ManyToManyField(
        Articulo,
        through="Stock",
        blank=True
    )
    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
        null=True,
        blank=True
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
        null=True,
        blank=True
    )
    history = HistoricalRecords()

    def __str__(self):
        return "{0} : {1}".format(
            self.clave.encode('utf-8'),
            self.descripcion.encode('utf-8')
        )

    class Meta:
        verbose_name_plural = "Almacenes"


class Stock(models.Model):
    almacen = models.ForeignKey(Almacen, on_delete=models.PROTECT)
    articulo = models.ForeignKey(Articulo, on_delete=models.PROTECT)
    costo = models.DecimalField(
        max_digits=20, decimal_places=4, default=0.0, blank=True
    )
    cantidad = models.DecimalField(
        max_digits=20, decimal_places=4, default=0.0)
    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
        null=True,
        blank=True
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
        null=True,
        blank=True
    )
    history = HistoricalRecords()

    def __str__(self):
        return "{0}) {1}".format(self.almacen, self.articulo)

    class Meta:
        unique_together = (('almacen', 'articulo'),)


class MovimientoCabecera(models.Model):
    fecha = models.DateTimeField()
    descripcion = models.CharField(max_length=144)
    almacen_origen = models.ForeignKey(
        Almacen, related_name="origen", null=True, blank=True)
    almacen_destino = models.ForeignKey(Almacen, related_name="destino")
    persona_recibe = models.CharField(max_length=144, blank=True)
    persona_entrega = models.CharField(max_length=144, blank=True)
    estado = models.CharField(
        max_length=4,
        choices=MOVIMIENTO_ESTADO,
        default="CAP",
        blank=True
    )
    tipo = models.CharField(
        max_length=4,
        choices=MOVIMIENTO_TIPO,
    )
    clasificacion = models.CharField(
        max_length=4,
        choices=MOVIMIENTO_CLASIFICACION,
        default='AJU'
    )
    orden_trabajo = models.ForeignKey(
        'trabajos.OrdenTrabajo', null=True, blank=True)
    usuario = models.ForeignKey(User, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.descripcion.encode('utf-8')


class MovimientoDetalle(models.Model):
    cantidad = models.DecimalField(
        max_digits=20, decimal_places=4, default=0.0)
    articulo = models.ForeignKey(Articulo)
    cabecera = models.ForeignKey(MovimientoCabecera)
    history = HistoricalRecords()

inventarios/templates/salida/formulario.html
{% extends 'master.html' %}

{% load static from staticfiles %}

{% block title %} CoreM - Salidas {% endblock title %}

{% block css %}

<!-- Kendo -->
<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.rtl.min.css' %}"/>
<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.common-bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.bootstrap.min.css' %}"/>


<!-- Select2 -->
<link rel="stylesheet" href="{% static 'libs/plugins/select2/select2.min.css' %}"/>

<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{% static 'libs/plugins/datepicker/datepicker3.css' %}">

<!-- CoreM -->
<link rel="stylesheet" href="{% static 'grid.css' %}"/>

{% endblock css %}

{% block contenido %}
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
	<span id="titulo">Salidas</span>
	<small>{{ operation }}</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="{% url 'dashboards:inicio' %}"><i class="fa fa-home"></i> Inicio</a></li>
		<li><a href="{% url 'inventarios:salidas_lista' %}">Salidas</a></li>
		<li class="active">Nuevo</li>

	</ol>
</section>
<!-- Main content -->
<section class="content" id="contenido">
	<div class="row">
		<div class="col-md-12">
			<!-- Formulario -->
			<div class="box box-solid box-primary" id="id_panel">
				<div class="box-header with-border">
					<h3 class="box-title">Entrada</h3>
					<div class="box-tools pull-right">
						<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div>
				</div>
				<!-- /.box-header -->
				<form role="form" action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
					<div class="box-body">
						{% if id_cabecera %}
						<input type="hidden" id="id_cabecera" value="{{ id_cabecera }}" name="id_cabecera">
						{% else %}
						<input type="hidden" id="id_tipo" name="tipo" value="ENT">
						{% endif %}
						<div class="row">
							<div class="form-group input-group-sm col-sx-12 col-sm-7 col-md-7 {% if form.descripcion.field.required %} has-warning {% endif %} {% if form.descripcion.errors %} has-error {% endif %}">
								<label for="{{ form.descripcion.id_for_label }}">
								<i class="fa {% if form.descripcion.field.required %} fa-asterisk {% endif %} {% if form.descripcion.errors %} fa-circle-o {% endif %}"></i>
								Descripción</label>
								{{ form.descripcion }}
								{% for error in form.descripcion.errors %}
								<span class="help-block">{{ error }}</span>
								{% endfor %}
							</div>
							<div class="form-group input-group-sm col-sx-12 col-sm-5 col-md-5 {% if form.fecha.field.required %} has-warning {% endif %} {% if form.fecha.errors %} has-error {% endif %} ">

								<label for="{{ form.fecha.id_for_label}}">
									<i class="fa {% if form.fecha.field.required %} fa-asterisk {% endif %} {% if form.fecha.errors %} fa-circle-o {% endif %}"></i>
									Fecha
								</label>

								<div class="form-group input-group">
					            	<div class="input-group-addon">
					                	<i class="fa fa-calendar"></i>
					            	</div>
					                {{ form.fecha }}
					            </div>

					            {% for error in form.fecha.errors %}
								    <span class="help-block">{{ error }}</span>
									{% endfor %}						
					        </div>
						</div>
						<div class="row">
							<div class="form-group input-group-sm col-sx-12 col-sm-6 col-md-6 {% if form.almacen_origen.field.required %} has-warning {% endif %} {% if form.almacen_origen.errors %} has-error {% endif %}">
								<label for="{{ form.almacen_origen.id_for_label }}">
								<i class="fa {% if form.almacen_origen.field.required %} fa-asterisk {% endif %} {% if form.almacen_origen.errors %} fa-circle-o {% endif %}"></i>
								Almacén Origen</label>
								{{ form.almacen_origen }}
								{% for error in form.almacen_origen.errors %}
								<span class="help-block">{{ error }}</span>
								{% endfor %}
								
							</div>
							<div class="form-group input-group-sm col-sx-12 col-sm-6 col-md-6 {% if form.almacen_destino.field.required %} has-warning {% endif %} {% if form.almacen_destino.errors %} has-error {% endif %}">
								<label for="{{ form.almacen_destino.id_for_label }}">
								<i class="fa {% if form.almacen_destino.field.required %} fa-asterisk {% endif %} {% if form.almacen_destino.errors %} fa-circle-o {% endif %}"></i>
								Almacén Destino</label>
								{{ form.almacen_destino }}
								{% for error in form.almacen_destino.errors %}
								<span class="help-block">{{ error }}</span>
								{% endfor %}
								
							</div>
							<div class="form-group input-group-sm col-sx-12 col-sm-3 col-md-3"></div>
							<div class="form-group input-group-sm col-sx-12 col-sm-3 col-md-3"></div>
						</div>
						<div class="row">
							
					        <div class="form-group input-group-sm col-sx-12 col-sm-6 col-md-6 {% if form.persona_recibe.field.required %} has-warning {% endif %} {% if form.persona_recibe.errors %} has-error {% endif %}">
								<label for="{{ form.persona_recibe.id_for_label }}">
								<i class="fa {% if form.persona_recibe.field.required %} fa-asterisk {% endif %} {% if form.persona_recibe.errors %} fa-circle-o {% endif %}"></i>
								Persona Recibe</label>
								{{ form.persona_recibe }}
								{% for error in form.persona_recibe.errors %}
								<span class="help-block">{{ error }}</span>
								{% endfor %}
							</div>
							<div class="form-group input-group-sm col-sx-12 col-sm-6 col-md-6 {% if form.persona_entrega.field.required %} has-warning {% endif %} {% if form.persona_entrega.errors %} has-error {% endif %}">
								<label for="{{ form.persona_entrega.id_for_label }}">
								<i class="fa {% if form.persona_entrega.field.required %} fa-asterisk {% endif %} {% if form.persona_entrega.errors %} fa-circle-o {% endif %}"></i>
								Persona Entrega</label>
								{{ form.persona_entrega }}
								{% for error in form.persona_entrega.errors %}
								<span class="help-block">{{ error }}</span>
								{% endfor %}
							</div>
						</div>
					</div>
					<!-- /.box-body -->
					<div class="box-footer">
						<a class="btn btn-default" href="{% url 'inventarios:salidas_lista' %}">
							<i class="fa fa-arrow-circle-left"></i>
							Regresar
						</a>

						<button type="submit" id="boton_guardar" class="btn btn-success pull-right">
							<i class="fa fa-save"></i>
							{% if id_cabecera %} Actualizar {% else %} Guardar {% endif %}
						</button>
					</div>
				</form>
			</div>
			<!-- /.box -->
			{% if id_cabecera %}
			<form role="form" action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
			<div class="box box-info">
				<div class="box-header box-header-border">
					<h3 class="box-title">Detalle</h3>
					<div class="box-tools pull-right">
						<button type="button" id="boton_nuevo" class="btn bg-purple btn-sm">
						<i class="fa fa-plus-circle"></i>
						Nuevo
						</button>
						<button type="button" id="boton_exportar" class="btn bg-olive btn-sm">
						<i class="fa fa-file-excel-o"></i>
						Exportar
						</button>
					</div>
				</div>
				<div id="grid_principal">
				</div>
				<div class="box-footer">
					<input type="hidden" value="{{ id_cabecera }}" id="id_cabecera_stock" name="cabecera_stock">
					<div class="box-tools pull-left">
						<button type="submit" id="boton_finalizar" class="btn bg-olive btn-sm">
						<i class="fa fa-save"></i>
						Finalizar
						</button>
					</div>
				</div>
			</div>
			</form>
			{% endif %}
            <!-- /.box-body -->
          </div>
			<!-- /.box -->
		</div>
	</div>
	<div class="modal fade" id="modal_nuevo" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
		<div class="modal-dialog modal-default">
	        <div class="modal-content">
	            <div class="modal-header">
	                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	                <span aria-hidden="true">×</span></button>
	                <h4 class="modal-title">Agregar Articulo</h4>
	            </div>
	            
	            <div class="modal-body">
	            	<input type="hidden" id="cabecera" value="{{ id_cabecera }}" name="cabecera">
					<div class="row">
						<div id="articulo_contenedor" class="form-group input-group-sm col-sx-12 col-sm-12 col-md-12 has-warning select2--fix">
							<label for="articulo">
							<i class="fa fa-asterisk"></i>
							Articulo</label>
							
							<select name="articulo" id="id_articulo" class="form-control"></select>
							
							<span class="help-block hidden" id="articulo_mensaje">Este campo es requerido.</span>			
					    </div>
					</div>
					<div class="row">
						<div id="cantidad_contenedor" class="form-group input-group-sm col-sx-12 col-sm-12 col-md-12 has-warning">
							<label for="cantidad">
							<i class="fa fa-asterisk"></i>
							Cantidad</label>
							<input type="text" class="form-control" name="cantidad" id="id_cantidad">
							<span class="help-block hidden" id="cantidad_mensaje">Este campo es requerido.</span>
						</div>
					</div>
	            </div>

	            <div class="modal-footer">
		            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">
		            	<i class="fa fa-close"></i>
		            	Cerrar
		            </button>
		            <button type="button" id="boton_guardar_detalle" class="btn btn-success">
		            	<i class="fa fa-save"></i>
		            	Guardar
		            </button>
	            </div>
	        </div>
	            <!-- /.modal-content -->
	    </div>
	</div>
</section>
<!-- /. Main content -->
{% endblock contenido %}

{% block scripts %}

<!-- Kendo Js -->
<script src="{% static 'libs/plugins/kendo_2015_2_624/js/cultures/kendo.culture.es-MX.min.js' %}"></script>
<script src="{% static 'libs/plugins/kendo_2015_2_624/js/kendo.web.min.js' %}"></script>

<!-- Select2 -->
<script src="{% static 'libs/plugins/select2/select2.full.min.js' %}"></script>

<!-- bootstrap datepicker -->
<script src="{% static 'libs/plugins/datepicker/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'libs/plugins/datepicker/locales/bootstrap-datepicker.es.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>

<!-- CoreM -->
<script src="{% static 'salida/formulario.js' %}"></script>

{% endblock scripts %}