dashboards/urls.py
# -*- coding: utf-8 -*-

# Librerias Django:

# Urls
from django.conf.urls import url

# Vistas
from .views import Inicio

app_name = "dashboards"

urlpatterns = [

    url(
        r'^inicio/$',
        Inicio.as_view(),
        name='inicio'
    ),
]

home/urls.py
# -*- coding: utf-8 -*-

# Librerias django:
# from django.conf.urls import url

# Vistas:
# from .views import Index

# urlpatterns = [
#     url(r'^index/$', Index.as_view(), name='home.index'),
# ]

inventarios/urls.py
# -*- coding: utf-8 -*-

# Librerias Django:
from django.conf.urls import url

# Vistas:
from .views import AlmacenListView
from .views import AlmacenCreateView
from .views import AlmacenUpdateView

from .views import StockListView

from .views import UdmArticuloListView
from .views import UdmArticuloCreateView
from .views import UdmArticuloUpdateView

from .views import ArticuloListView
from .views import ArticuloCreateView
from .views import ArticuloUpdateView

from .views import ArticuloAnexoTextoView
from .views import ArticuloAnexoImagenView
from .views import ArticuloAnexoArchivoView

from .views import EntradaListView
from .views import EntradaCabeceraCreateView
from .views import EntradaCabeceraUpdateView
from .views import SalidaListView
from .views import SalidaCabeceraCreateView
from .views import SalidaCabeceraUpdateView
from .views import EntradaSaldoListView
from .views import EntradaSaldoCreateView
from .views import EntradaSaldoUpdateView
from .views import EntradaCompraListView
from .views import EntradaCompraCreateView
from .views import EntradaCompraUpdateView

app_name = "inventarios"

urlpatterns = [

    # ----------------- ALMACEN ----------------- #

    url(
        r'^almacenes/$',
        AlmacenListView.as_view(),
        name='almacenes_lista'
    ),
    url(
        r'^almacenes/nuevo/$',
        AlmacenCreateView.as_view(),
        name='almacenes_nuevo'
    ),
    url(
        r'^almacenes/editar/(?P<pk>.*)/$',
        AlmacenUpdateView.as_view(),
        name='almacenes_editar'
    ),


    # ----------------- UDM ARTICULO ----------------- #

    url(
        r'udmarticulo/$',
        UdmArticuloListView.as_view(),
        name='udms_articulo_lista'
    ),
    url(
        r'udmarticulo/nuevo/$',
        UdmArticuloCreateView.as_view(),
        name='udms_articulo_nuevo'
    ),
    url(
        r'udmarticulo/editar/(?P<pk>\d+)/$',
        UdmArticuloUpdateView.as_view(),
        name='udms_articulo_editar'
    ),



    # ----------------- ARTICULOS ----------------- #

    url(
        r'^articulos/$',
        ArticuloListView.as_view(),
        name='articulos_lista'
    ),
    url(
        r'^articulos/nuevo/$',
        ArticuloCreateView.as_view(),
        name='articulos_nuevo'
    ),
    url(
        r'^articulos/editar/(?P<pk>.*)/$',
        ArticuloUpdateView.as_view(),
        name='articulos_editar'
    ),


    # ----------------- ARTICULOS - ANEXOS ----------------- #

    url(
        r'articulos/anexos/(?P<pk>\d+)/texto/$',
        ArticuloAnexoTextoView.as_view(),
        name='anexar_texto'
    ),
    url(
        r'^articulos/anexos/(?P<pk>\d+)/imagen/$',
        ArticuloAnexoImagenView.as_view(),
        name='anexar_imagen'
    ),
    url(
        r'^articulos/anexos/(?P<pk>\d+)/archivo/$',
        ArticuloAnexoArchivoView.as_view(),
        name='anexar_archivo'
    ),


    # ----------------- STOCK ----------------- #

    url(
        r'^stock/(?P<almacen>\d+)/(?P<articulo>\d+)/$',
        StockListView.as_view(),
        name='stock'
    ),


    # ----------------- ENTRADAS ----------------- #

    url(
        r'entradas/$',
        EntradaListView.as_view(),
        name='entradas_lista'
    ),
    url(
        r'entradas/nuevo/$',
        EntradaCabeceraCreateView.as_view(),
        name='entradas_nuevo'
    ),
    url(
        r'entradas/editar/(?P<pk>\d+)/$',
        EntradaCabeceraUpdateView.as_view(),
        name='entradas_editar'
    ),
    url(
        r'entradas/saldo_inicial/$',
        EntradaSaldoListView.as_view(),
        name='entradas_saldoinicial_lista'
    ),
    url(
        r'entradas/saldo_inicial/nuevo/$',
        EntradaSaldoCreateView.as_view(),
        name='entradas_saldoinicial_nuevo'
    ),
    url(
        r'entradas/saldo_inicial/editar/(?P<pk>\d+)/$',
        EntradaSaldoUpdateView.as_view(),
        name='entradas_saldoinicial_editar'
    ),
    url(
        r'entradas/compras/$',
        EntradaCompraListView.as_view(),
        name='entradas_compras_lista'
    ),
    url(
        r'entradas/saldo_inicial/nuevo/$',
        EntradaCompraCreateView.as_view(),
        name='entradas_compras_nuevo'
    ),
    url(
        r'entradas/saldo_inicial/editar/(?P<pk>\d+)/$',
        EntradaCompraUpdateView.as_view(),
        name='entradas_compras_editar'
    ),
    # ----------------- SALIDAS ----------------- #
    url(
        r'salidas/$',
        SalidaListView.as_view(),
        name='salidas_lista'
    ),
    url(
        r'salidas/nuevo/$',
        SalidaCabeceraCreateView.as_view(),
        name='salidas_nuevo'
    ),
    url(
        r'salidas/editar/(?P<pk>\d+)/$',
        SalidaCabeceraUpdateView.as_view(),
        name='salidas_editar'
    ),
]

home/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
# from django.core.exceptions import ValidationError

from .validators import validate_image
from .utilities import get_FilePath
from .utilities import get_ImagePath
# from .validators import valid_extension
# Otros modelos

from activos.models import Equipo
from inventarios.models import Articulo
from trabajos.models import OrdenTrabajo


class AnexoArchivo(models.Model):
    equipo = models.ForeignKey(Equipo, null=True, blank=True)
    articulo = models.ForeignKey(Articulo, null=True, blank=True)
    orden_trabajo = models.ForeignKey(OrdenTrabajo, null=True, blank=True)
    archivo = models.FileField(upload_to=get_FilePath)
    descripcion = models.CharField(max_length=255, null=True, blank=True)


class AnexoTexto(models.Model):
    equipo = models.ForeignKey(Equipo, null=True, blank=True)
    articulo = models.ForeignKey(Articulo, null=True, blank=True)
    orden_trabajo = models.ForeignKey(OrdenTrabajo, null=True, blank=True)
    titulo = models.CharField(max_length=60)
    texto = models.CharField(max_length=255, null=True, blank=True)


class AnexoImagen(models.Model):
    equipo = models.ForeignKey(Equipo, null=True, blank=True)
    articulo = models.ForeignKey(Articulo, null=True, blank=True)
    orden_trabajo = models.ForeignKey(OrdenTrabajo, null=True, blank=True)
    ruta = models.ImageField(upload_to=get_ImagePath,
                             validators=[validate_image])
    descripcion = models.CharField(max_length=255, null=True)

inventarios/views.py
# -*- coding: utf-8 -*-

# LIBRERIAS Django

# Django DB
# from django.db import transaction

# Django Atajos:
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

# Django Urls:
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy
# from django.http import HttpResponse

# Django Generic Views
from django.views.generic.base import View
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import TemplateView

# Modelos:
# from .models import Udm
from .models import Articulo
from .models import UdmArticulo
from .models import Almacen
from .models import Stock
from .models import MovimientoCabecera
from .models import MovimientoDetalle
from home.models import AnexoImagen
from home.models import AnexoArchivo
from home.models import AnexoTexto
from django.contrib.auth.models import User

# Formularios:
from .forms import AlmacenForm
from .forms import ArticuloFilterForm
from .forms import ArticuloForm
from .forms import MovimientoCabeceraFilterForm
from .forms import MovimientoCabeceraForm
from .forms import StockFilterForm
from .forms import MovimientoDetalleForm
from .forms import UdmArticuloForm
from .forms import EntradaSaldoForm
from .forms import EntradaCompraForm
from home.forms import AnexoTextoForm
from home.forms import AnexoImagenForm
from home.forms import AnexoArchivoForm

# API Rest:
from rest_framework import viewsets
from rest_framework import filters
from django_filters.rest_framework import DjangoFilterBackend


# API Rest - Serializadores:
from .serializers import AlmacenSerializer
from .serializers import UdmArticuloSerializer
from .serializers import ArticuloSerializer
from .serializers import StockSerializer
from .serializers import MovimientoCabeceraSerializer
from .serializers import MovimientoDetalleSerializer
# from .serializers import SalidaCabeceraSerializer
from home.serializers import AnexoTextoSerializer
from home.serializers import AnexoImagenSerializer
from home.serializers import AnexoArchivoSerializer

# API Rest - Paginacion:
from .pagination import GenericPagination

# API Rest - Filtros:
from .filters import ArticuloFilter
from .filters import MovimientoCabeceraFilter
from .filters import StockFilter

# ----------------- ALMACEN ----------------- #


class AlmacenListView(TemplateView):
    template_name = 'almacen/lista.html'


class AlmacenCreateView(CreateView):
    model = Almacen
    form_class = AlmacenForm
    template_name = 'almacen/formulario.html'
    success_url = reverse_lazy('inventarios:almacenes_lista')

    def get_context_data(self, **kwargs):
        context = super(AlmacenCreateView, self).get_context_data(**kwargs)

        data = {
            'operation': "Nuevo"
        }

        context.update(data)

        return context


class AlmacenUpdateView(UpdateView):
    model = Almacen
    form_class = AlmacenForm
    template_name = 'almacen/formulario.html'
    success_url = reverse_lazy('inventarios:almacenes_lista')

    def get_context_data(self, **kwargs):
        context = super(AlmacenUpdateView, self).get_context_data(**kwargs)

        data = {
            'operation': "Editar"
        }

        context.update(data)

        return context


class AlmacenAPI(viewsets.ModelViewSet):
    queryset = Almacen.objects.all()
    serializer_class = AlmacenSerializer

    filter_backends = (filters.SearchFilter,)
    search_fields = ('clave', 'descripcion',)


# ----------------- UDM ARTICULO ----------------- #

class UdmArticuloListView(TemplateView):
    template_name = 'udm_articulo/lista.html'


class UdmArticuloCreateView(CreateView):
    model = UdmArticulo
    form_class = UdmArticuloForm
    template_name = 'udm_articulo/formulario.html'
    success_url = reverse_lazy('inventarios:udms_articulo_lista')
    operation = "Nueva"

    def get_context_data(self, **kwargs):
        contexto = super(
            UdmArticuloCreateView,
            self
        ).get_context_data(**kwargs)
        contexto['operation'] = self.operation
        return contexto


class UdmArticuloUpdateView(UpdateView):
    model = UdmArticulo
    form_class = UdmArticuloForm
    template_name = 'udm_articulo/formulario.html'
    success_url = reverse_lazy('inventarios:udms_articulo_lista')
    operation = "Editar"

    def get_context_data(self, **kwargs):
        contexto = super(
            UdmArticuloUpdateView,
            self
        ).get_context_data(**kwargs)
        contexto['operation'] = self.operation
        return contexto


class UdmArticuloAPI(viewsets.ModelViewSet):
    queryset = UdmArticulo.objects.all()
    serializer_class = UdmArticuloSerializer

    filter_backends = (filters.SearchFilter,)
    search_fields = ('clave', 'descripcion',)


class UdmArticuloAPI2(viewsets.ModelViewSet):
    queryset = UdmArticulo.objects.all()
    serializer_class = UdmArticuloSerializer
    filter_backends = (DjangoFilterBackend,)
    filter_fields = ('id',)


# ----------------- ARTICULOS ----------------- #


class ArticuloListView(View):
    def __init__(self):
        self.template_name = 'articulo/lista.html'

    def get(self, request):

        formulario = ArticuloFilterForm()

        contexto = {
            'form': formulario
        }

        return render(request, self.template_name, contexto)

    def post(self, request):
        return render(request, self.template_name, {})


class ArticuloCreateView(View):

    def __init__(self):
        self.template_name = 'articulo/formulario.html'

    def obtener_UrlImagen(self, _imagen):
        imagen = ''

        if _imagen:
            imagen = _imagen.url

        return imagen

    def get(self, request):

        formulario = ArticuloForm()
        contexto = {
            'form': formulario,
            'operation': "Nuevo"
        }
        return render(request, self.template_name, contexto)

    def post(self, request):

        formulario = ArticuloForm(request.POST)

        if formulario.is_valid():

            datos_formulario = formulario.cleaned_data
            articulo = Articulo()
            articulo.clave = datos_formulario.get('clave')
            articulo.descripcion = datos_formulario.get('descripcion')
            articulo.tipo = datos_formulario.get('tipo')
            articulo.udm = datos_formulario.get('udm')
            articulo.estado = datos_formulario.get('estado')
            articulo.clave_jde = datos_formulario.get('clave_jde')
            articulo.imagen = datos_formulario.get('imagen')

            articulo.save()

            return redirect(
                reverse('inventarios:articulos_lista')
            )
        contexto = {
            'form': formulario,
            'imagen': self.obtener_UrlImagen(articulo.imagen),
            'operation': "Nuevo"
        }

        return render(request, self.template_name, contexto)


class ArticuloUpdateView(View):
    def __init__(self):
        self.template_name = 'articulo/formulario.html'

    def obtener_UrlImagen(self, _imagen):
        imagen = ''

        if _imagen:
            imagen = _imagen.url

        return imagen

    def get(self, request, pk):

        articulo = get_object_or_404(Articulo, pk=pk)

        formulario = ArticuloForm(
            instance=articulo
        )

        contexto = {
            'form': formulario,
            'operation': "Editar",
            'imagen': self.obtener_UrlImagen(articulo.imagen)
        }

        return render(request, self.template_name, contexto)

    def post(self, request, pk):

        articulo = get_object_or_404(Articulo, pk=pk)
        formulario = ArticuloForm(
            request.POST,
            request.FILES,
            instance=articulo
        )

        if formulario.is_valid():

            articulo = formulario.save(commit=False)
            articulo.save()

            return redirect(
                reverse('inventarios:articulos_lista')
            )

        contexto = {
            'form': formulario,
            'operation': "Editar",
            'imagen': self.obtener_UrlImagen(articulo.imagen)
        }
        return render(request, self.template_name, contexto)


class ArticuloAPI(viewsets.ModelViewSet):
    queryset = Articulo.objects.all()
    serializer_class = ArticuloSerializer
    pagination_class = GenericPagination

    filter_backends = (DjangoFilterBackend,)
    filter_class = ArticuloFilter


class ArticuloAPI2(viewsets.ModelViewSet):
    queryset = Articulo.objects.all()
    serializer_class = ArticuloSerializer
    filter_backends = (DjangoFilterBackend,)
    filter_class = ArticuloFilter

# ----------------- ARTICULO - ANEXOS ----------------- #


class ArticuloAnexoTextoView(View):

    def __init__(self):
        self.template_name = 'articulo/anexos/anexos_texto.html'

    def get(self, request, pk):
        id_articulo = pk
        anexos = AnexoTexto.objects.filter(articulo=id_articulo)
        articulo = Articulo.objects.get(id=id_articulo)
        form = AnexoTextoForm()

        contexto = {
            'form': form,
            'id': id_articulo,
            'articulo': articulo,
            'anexos': anexos,
        }

        return render(request, self.template_name, contexto)

    def post(self, request, pk):
        id_articulo = pk
        form = AnexoTextoForm(request.POST)
        anexos = AnexoTexto.objects.filter(articulo=id_articulo)
        articulo = Articulo.objects.get(id=id_articulo)

        if form.is_valid():
            texto = form.save(commit=False)
            texto.articulo_id = id_articulo
            texto.save()
            anexos = AnexoTexto.objects.filter(articulo=id_articulo)
            form = AnexoTextoForm()
        return render(request, 'articulo/anexos/anexos_texto.html',
                      {'form': form, 'id': id_articulo, 'anexos': anexos,
                       'articulo': articulo})

inventarios/templates/articulo/anexos/anexos_archivo.html
{% extends 'master.html' %}
{% load filename %}
{% load static from staticfiles %}

{% block title %} Anexos Articulo {% endblock title %}

{% block css %}

	<!-- Kendo -->

	<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.rtl.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.common.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.default.min.css' %}"/>

{% endblock css %}	

{% block contenido %}

	<!-- Content Header (Page header) -->
	<section class="content-header">
	  <h1>
	    <span id="titulo">Articulos</span>
	    <small>Anexos</small>
	  </h1>
	  <ol class="breadcrumb">
	    <li><a href="{% url 'dashboards:inicio' %}"><i class="fa fa-home"></i> Inicio</a></li>
	    <li><a href="{% url 'inventarios:articulos_lista' %}">Articulos</a></li>
	    <li class="active">Anexos</li>
	  </ol>
	</section>

	<!-- Main content -->
	<section class="content" id="contenido">

		<div class="row">
	        <div class="col-md-12">
				<input id="id_equipo" type="hidden" value="{{ id }}">
		        <div class="box box-info">
		            <div class="box-header with-border">
		           		  <div class="box-header with-border">
		              <h3 class="box-title">Articulo: <strong> {{ articulo.clave }} - {{ articulo.descripcion }}</strong></h3>
		            </div>
					<div class="box-body">
						<a href= "/articulos/anexos/{{id}}/texto" class="btn btn-app">
				           	<i class="fa fa-text-width"></i> Texto
				        </a>
				        <a href="/articulos/anexos/{{id}}/imagen" class="btn btn-app">
				        	<i class="fa fa-file-image-o"></i> Imagen
				        </a>
				        <a class="btn btn-app btn-primary active">
				            <i class="fa fa-file-o"></i> Archivo
				        </a>
					</div>
		        </div>	
		            
		            <!-- /.box-header -->	
		        </div>
		        <div class="box box-solid box-primary collapsed-box" id="id_panel">
		            <div class="box-header with-border">
		            	<h3 class="box-title">Anexar Archivo</h3>

			          	<div class="box-tools pull-right">
			            	<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
			          	</div>	              
		            </div>
	                <div class="box-body">
						<form role="form" action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
		              		
		               			
					    		<div class="row">
					    			<div class="col-sm-10 col-md-offset-1">
										{% for field in form %}
					    				<div class="form-group {% if field.field.required %} has-warning {% endif %} {% if field.errors %} has-error {% endif %}">
					    					
					    						<label for="{{ field.label }}">
					       		 				<i class="fa {% if field.field.required %} fa-asterisk {% endif %} {% if field.field.errors %} fa-asterisk {% endif %}"></i>
												{{ field.label }}
					       		 				</label>

					        					{{ field }}
					        				
					        					{% for error in field.errors %}
		              						<div class="help-block text-right" id="{{ field.label }}-error">
		              							{{ error }}
		              						</div>
		              							{% endfor %}
					    				</div>
					    				{% endfor %}
					   				</div>
					   			</div>
					   			
					   		
		              	
		              <!-- /.box-body -->  
		              
		              <!-- /.box-footer -->

	        	</div>
	        		 <div class="box-footer">
	        		 	<div class="col-xs-12">
							<button type="submit"  class="btn btn-success pull-right">Guardar</button>
						</div>
	              	</div>
	              </form>
	    		</div> 	
	          <!-- /.box -->			

		</div>
</div>
		<div class="row">
			<div class="box box-solid">
				{% for anexo in anexos %}
				
					<div class="col-md-4" id="{{ anexo.id }}">
		          		<div class="box box-solid">
		            		<div class="box-header with-border">
		              			<div class="pull-right">
		              				<button data-action="{{ anexo.id }}" class="btn btn-danger btn-sm"><i class="fa fa-trash" title="Eliminar"></i></button>
		            			</div>	
		            		
		              			<h3 class="box-title">
		              			<i class="fa fa-file-o"></i>
		              			{{ anexo.descripcion }}
		              			</h3>
		            		</div>
		            		<!-- /.box-header -->
				            <div class="box-body">
				            	<a href="{{MEDIA_URL}}{{ anexo.archivo }}" download=""><p align="center"><strong align="center">{{ anexo.archivo|filename }}</strong></p></a>
				            </div>
		            		<!-- /.box-body -->
		          		</div>
          <!-- /.box -->
        			</div>
        	{% endfor %}
 
		</div>
			</div>
		
	</section>
	<!-- /. Main content -->

{% endblock contenido %}

{% block scripts %}

	<!-- Kendo -->

	<script src="{% static 'libs/plugins/kendo_2015_2_624/js/cultures/kendo.culture.es-MX.min.js' %}"></script>
	<script src="{% static 'libs/plugins/kendo_2015_2_624/js/kendo.web.min.js' %}"></script>

	<!-- CoreM -->

	<script src="{% static 'articulo/anexos/archivo.js' %}"></script>

{% endblock scripts %}

inventarios/templates/articulo/anexos/anexos_imagen.html
{% extends 'master.html' %}

{% load static from staticfiles %}

{% block title %} Anexos Articulo {% endblock title %}

{% block css %}

	<!-- Kendo -->

	<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.rtl.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.common.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.default.min.css' %}"/>

{% endblock css %}

{% block contenido %}

	<!-- Content Header (Page header) -->
	<section class="content-header">
	  <h1>
	    <span id="titulo">Articulos</span>
	    <small>Anexos</small>
	  </h1>
	  <ol class="breadcrumb">
	    <li><a href="{% url 'dashboards:inicio' %}"><i class="fa fa-home"></i> Inicio</a></li>
	    <li><a href="{% url 'inventarios:articulos_lista' %}">Articulos</a></li>
	    <li class="active">Anexos</li>
	  </ol>
	</section>

	<!-- Main content -->
	<section class="content" id="contenido">

		<div class="row">
	        <div class="col-md-12">
			<input id="id_equipo" type="hidden" value="{{ id }}">
	          <!-- Filtros -->
	          <div class="box box-info">
	            <div class="box-header with-border">
	            	<div class="box-header with-border">
		             <h3 class="box-title">Articulo: <strong> {{ articulo.clave }} - {{ articulo.descripcion }}</strong></h3>
		            </div>
		            <div class="box-body">
		            	<a href= "/articulos/anexos/{{id}}/texto" class="btn btn-app">
			           	<i class="fa fa-text-width"></i> Texto
			        </a>
			        <a class="btn btn-app btn-primary active">
			        	<i class="fa fa-file-image-o"></i> Imagen
			        </a>
			        <a href="/articulos/anexos/{{id}}/archivo" class="btn btn-app">
			            <i class="fa fa-file-o"></i> Archivo
			        </a>
		            </div>
	            	
	            </div>
	        </div>
	            <!-- /.box-header -->
				     <div class="box box-solid box-primary collapsed-box" id="id_panel">
		            <div class="box-header with-border">
		            	<h3 class="box-title">Anexar Imagen</h3>

			          	<div class="box-tools pull-right">
			            	<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
			          	</div>	              
		            </div>
	                <div class="box-body">
						<form role="form" action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
		              		
		               			
					    		<div class="row">
					    			<div class="col-sm-10 col-md-offset-1">
					    				{% for field in form %}
					    				<div class="form-group {% if field.field.required %} has-warning {% endif %} {% if field.errors %} has-error {% endif %}">
					    					
					    						<label for="{{ field.label }}">
					       		 				<i class="fa {% if field.field.required %} fa-asterisk {% endif %} {% if field.field.errors %} fa-asterisk {% endif %}"></i>
												{{ field.label }}
					       		 				</label>

					        					{{ field }}
					        				
					        					{% for error in field.errors %}
		              						<div class="help-block text-right" id="{{ field.label }}-error">
		              							{{ error }}
		              						</div>
		              							{% endfor %}
					    				</div>
					    				{% endfor %}
					   				</div>
					   			</div>
					   			
					   		
		              	
		              <!-- /.box-body -->  
		              
		              <!-- /.box-footer -->

	        	</div>
	        		 <div class="box-footer">
		        		 <div class="col-xs-12">

		        		 	 <button type="submit"  class="btn btn-success pull-right">Guardar</button>
		        		 </div>
	              	</div>

	              </form>
	    		</div> 	
	          <!-- /.box -->			

		</div>
</div>
		<div class="row">
		{% for anexo in anexos %}
			<div class="col-md-4" id="{{ anexo.id }}">
          		<div class="box box-solid">
            		<div class="box-header with-border">
            		<i class="fa fa-file-image-o"></i>
              			<div class="pull-right">
              				<button data-action="{{ anexo.id }}" class="btn btn-danger btn-sm"><i class="fa fa-trash" title="Eliminar"></i></button>
            				<a href="{{MEDIA_URL}}{{ anexo.ruta }}" download class="btn btn-default btn-sm"><i class="fa fa-download" title="Descargar"></i></a>
            			</div>	
            		
              			<h3 class="box-title">{{ anexo.descripcion }}</h3>
            		</div>
            		<!-- /.box-header -->
		            <div class="box-body">
		            	<div align="center">
		            	<img src="{{MEDIA_URL}}{{ anexo.ruta }}" alt="{{ anexo.descripcion }}" width="300px", height="200px" >   
		            	</div>
		            	
		            </div>
            		<!-- /.box-body -->
          		</div>
          <!-- /.box -->
        	</div>
        	{% endfor %}
 
		</div>
	</section>
	<!-- /. Main content -->

{% endblock contenido %}

{% block scripts %}

	<!-- Kendo -->

	<script src="{% static 'libs/plugins/kendo_2015_2_624/js/cultures/kendo.culture.es-MX.min.js' %}"></script>
	<script src="{% static 'libs/plugins/kendo_2015_2_624/js/kendo.web.min.js' %}"></script>

	<!-- CoreM -->

	<script src="{% static 'articulo/anexos/imagen.js' %}"></script>



{% endblock scripts %}