dashboards/urls.py
# -*- coding: utf-8 -*-

# Librerias Django:

# Urls
from django.conf.urls import url

# Vistas
from .views import Inicio

app_name = "dashboards"

urlpatterns = [

    url(
        r'^inicio/$',
        Inicio.as_view(),
        name='inicio'
    ),
]

home/urls.py
# -*- coding: utf-8 -*-

# Librerias django:
# from django.conf.urls import url

# Vistas:
# from .views import Index

# urlpatterns = [
#     url(r'^index/$', Index.as_view(), name='home.index'),
# ]

trabajos/urls.py
# -*- coding: utf-8 -*-

# Librerias Django:
from django.conf.urls import url

# Vistas:
from .views import OrdenTrabajoListView
from .views import OrdenTrabajoCreateView
from .views import OrdenTrabajoUpdateView

from .views import ActividadListView
from .views import MaterialListView
from .views import ManoObraListView
from .views import ServicioExternoListView

from .views import OrdenAnexoTextoView
from .views import OrdenAnexoImagenView
from .views import OrdenAnexoArchivoView


app_name = 'trabajos'

urlpatterns = [

    # ----------------- ORDEN DE TRABAJO ----------------- #
    url(
        r'^ordenes/$',
        OrdenTrabajoListView.as_view(),
        name='ordenes_lista'
    ),

    url(
        r'^ordenes/nuevo/$',
        OrdenTrabajoCreateView.as_view(),
        name='ordenes_nueva'
    ),
    url(
        r'^ordenes/editar/(?P<pk>.*)/$',
        OrdenTrabajoUpdateView.as_view(),
        name='ordenes_editar'
    ),

    # ----------------- ACTIVIDADES ----------------- #

    url(
        r'^ordenes/(?P<pk>.*)/actividades/$',
        ActividadListView.as_view(),
        name='actividades_lista'
    ),

    # ----------------- MATERIAL ----------------- #

    url(
        r'^ordenes/(?P<pk>.*)/materiales/$',
        MaterialListView.as_view(),
        name='material_lista'
    ),

    # ----------------- MANO OBRA ----------------- #

    url(
        r'^ordenes/(?P<pk>.*)/mano_obra/$',
        ManoObraListView.as_view(),
        name='mano_obra_lista'
    ),

    # ----------------- SERVICIO EXTERNO ----------------- #

    url(
        r'^ordenes/(?P<pk>.*)/servicios/$',
        ServicioExternoListView.as_view(),
        name='servicio_externo_lista'
    ),

    # ----------------- ORDENES - ANEXOS ----------------- #
    url(
        r'ordenes/anexos/(?P<pk>\d+)/texto/$',
        OrdenAnexoTextoView.as_view(),
        name='orden_anexar_texto'
    ),
    url(
        r'^ordenes/anexos/(?P<pk>\d+)/imagen/$',
        OrdenAnexoImagenView.as_view(),
        name='orden_anexar_imagen'
    ),
    url(
        r'^ordenes/anexos/(?P<pk>\d+)/archivo/$',
        OrdenAnexoArchivoView.as_view(),
        name='orden_anexar_archivo'
    ),


]

trabajos/forms.py
# -*- coding: utf-8 -*-

# Django:
from django.forms import ModelForm
from django.forms import Form
from django.forms import TextInput
from django.forms import Select
from django.forms import CheckboxInput
from django.forms import Textarea
from django.forms import ChoiceField
from django.forms import CharField


# Modelos:
from activos.models import Equipo
from .models import OrdenTrabajo
# from .models import ORDEN_TIPO
# from .models import EQUIPO_ESTADO

# ----------------- ORDEN DE TRABAJO ----------------- #


class OrdenTrabajoForm(ModelForm):

    class Meta:
        model = OrdenTrabajo
        fields = '__all__'
        widgets = {
            'descripcion': TextInput(attrs={'class': 'form-control input-sm'}),
            'equipo': Select(attrs={'class': 'form-control input-sm select2'}),
            'tipo': Select(attrs={'class': 'form-control input-sm select2'}),
            'estado': Select(attrs={'class': 'form-control input-sm select2'}),
            'fecha_estimada_inicio': TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'data-date-format': 'yyyy-mm-dd'
                }
            ),
            'fecha_estimada_fin': TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'data-date-format': 'yyyy-mm-dd'
                }
            ),
            'fecha_real_inicio': TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'data-date-format': 'yyyy-mm-dd'
                }
            ),
            'fecha_real_fin': TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'data-date-format': 'yyyy-mm-dd'
                }
            ),
            'es_template': CheckboxInput(),


            'responsable': TextInput(
                attrs={'class': 'form-control input-sm select2'}
            ),
            'observaciones': Textarea(
                attrs={'class': 'form-control input-sm'}
            ),
        }
        labels = {
            'es_template': "Template"
        }


class OrdenTrabajoFiltersForm(Form):

    tipo = ChoiceField(
        widget=Select(attrs={'class': 'form-control input-sm  select2'})
    )
    estado = ChoiceField(
        widget=Select(
            attrs={'class': 'form-control input-sm  select2'}
        )
    )
    descripcion = CharField(
        widget=TextInput(attrs={'class': 'form-control input-sm'})
    )
    equipo = ChoiceField(
        widget=Select(
            attrs={'class': 'form-control input-sm  select2'}
        )
    )
    responsable = CharField(
        widget=TextInput(attrs={'class': 'form-control input-sm'})
    )

    def __init__(self, *args, **kwargs):

        super(OrdenTrabajoFiltersForm, self).__init__(*args, **kwargs)
        self.fields['equipo'].choices = self.get_Equipos()
        self.fields['tipo'].choices = self.get_Tipos(OrdenTrabajo.ORDEN_TIPO)
        self.fields['estado'].choices = self.get_Estados(
            OrdenTrabajo.ORDEN_ESTADO
        )

    def get_Tipos(self, _opciones):
        opciones = [('', '-------')]

        for registro in _opciones:
            opciones.append(registro)
        return opciones

    def get_Estados(self, _opciones):
        opciones = [('', '-------')]

        for registro in _opciones:
            opciones.append(registro)
        return opciones

    def get_Equipos(self):

        equipo = [('', '-------')]

        registros = Equipo.objects.all()

        for registro in registros:
            equipo.append(
                (
                    registro.tag,
                    "{} - {}".format(
                        registro.tag.encode('utf-8'),
                        registro.descripcion.encode('utf-8')
                    )
                )
            )

        return equipo

trabajos/views.py
# -*- coding: utf-8 -*-

# Django Atajos:
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

# Django Urls:
from django.core.urlresolvers import reverse

# Django Generic Views
from django.views.generic.base import View

# Modelos:
from .models import OrdenTrabajo
from .models import Actividad
from .models import ManoObra
from .models import Material
from .models import ServicioExterno

from home.models import AnexoTexto
from home.models import AnexoImagen
from home.models import AnexoArchivo

# Formularios:
from .forms import OrdenTrabajoForm
from home.forms import AnexoTextoForm
from home.forms import AnexoImagenForm
from home.forms import AnexoArchivoForm

# API Rest & Json:
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend

# API Rest - Serializadores:
from .serializers import OrdenTrabajoSerializer
from .serializers import ActividadSerializer

from .serializers import ManoObraSerializer
from .serializers import MaterialSerializer
from .serializers import ServicioExternoSerializer

from home.serializers import AnexoTextoSerializer
from home.serializers import AnexoImagenSerializer
from home.serializers import AnexoArchivoSerializer


# API Rest - Paginacion:
from .pagination import GenericPagination

# API Rest - Filtros:
from .filters import OrdenTrabajoFilter

# Formulario Filtros
from .forms import OrdenTrabajoFiltersForm


# ----------------- ORDEN DE TRABAJO ----------------- #


class OrdenTrabajoListView(View):

    def __init__(self):
        self.template_name = 'orden_trabajo/lista.html'

    def get(self, _request):
        formulario = OrdenTrabajoFiltersForm()
        contexto = {
            'form': formulario
        }
        return render(_request, self.template_name, contexto)


class OrdenTrabajoCreateView(View):

    def __init__(self):
        self.template_name = 'orden_trabajo/formulario.html'

    def get(self, request):
        formulario = OrdenTrabajoForm()

        contexto = {
            'form': formulario,
            'operation': "Nueva"
        }

        return render(request, self.template_name, contexto)

    def post(self, request):

        formulario = OrdenTrabajoForm(request.POST)

        if formulario.is_valid():

            datos_formulario = formulario.cleaned_data
            orden = OrdenTrabajo()

            orden.equipo = datos_formulario.get('equipo')
            orden.descripcion = datos_formulario.get('descripcion')
            orden.tipo = datos_formulario.get('tipo')
            orden.estado = datos_formulario.get('estado')
            orden.responsable = datos_formulario.get('responsable')
            orden.fecha_estimada_inicio = datos_formulario.get(
                'fecha_estimada_inicio'
            )
            orden.fecha_estimada_fin = datos_formulario.get(
                'fecha_estimada_fin'
            )
            orden.fecha_real_inicio = datos_formulario.get('fecha_real_inicio')
            orden.fecha_real_fin = datos_formulario.get('fecha_real_fin')
            orden.observaciones = datos_formulario.get('observaciones')
            orden.es_template = datos_formulario.get('es_template')

            orden.save()

            return redirect(
                reverse(
                    'trabajos:actividades_lista',
                    kwargs={'pk': orden.id}
                )
            )

        contexto = {
            'form': formulario,
            'operation': "Nueva"
        }

        return render(request, self.template_name, contexto)


class OrdenTrabajoUpdateView(View):

    def __init__(self):
        self.template_name = 'orden_trabajo/formulario.html'

    def get(self, request, pk):

        orden = get_object_or_404(OrdenTrabajo, pk=pk)

        formulario = OrdenTrabajoForm(
            initial={
                'equipo': orden.equipo,
                'descripcion': orden.descripcion,
                'tipo': orden.tipo,
                'estado': orden.estado,
                'responsable': orden.responsable,
                'fecha_estimada_inicio': orden.fecha_estimada_inicio,
                'fecha_estimada_fin': orden.fecha_estimada_fin,
                'fecha_real_inicio': orden.fecha_real_inicio,
                'fecha_real_fin': orden.fecha_real_fin,
                'observaciones': orden.observaciones,
                'es_template': orden.es_template,
            }
        )

        contexto = {
            'form': formulario,
            'operation': "Editar",
            'orden': orden
        }

        return render(request, self.template_name, contexto)

    def post(self, request, pk):

        formulario = OrdenTrabajoForm(request.POST)

        orden = get_object_or_404(OrdenTrabajo, pk=pk)

        if formulario.is_valid():

            datos_formulario = formulario.cleaned_data

            orden.equipo = datos_formulario.get('equipo')
            orden.descripcion = datos_formulario.get('descripcion')
            orden.tipo = datos_formulario.get('tipo')
            orden.estado = datos_formulario.get('estado')
            orden.responsable = datos_formulario.get('responsable')
            orden.fecha_estimada_inicio = datos_formulario.get(
                'fecha_estimada_inicio'
            )
            orden.fecha_estimada_fin = datos_formulario.get(
                'fecha_estimada_fin'
            )
            orden.fecha_real_inicio = datos_formulario.get('fecha_real_inicio')
            orden.fecha_real_fin = datos_formulario.get('fecha_real_fin')
            orden.observaciones = datos_formulario.get('observaciones')
            orden.es_template = datos_formulario.get('es_template')

            orden.save()

            return redirect(
                reverse(
                    'trabajos:actividades_lista',
                    kwargs={'pk': orden.id}
                )
            )

        contexto = {
            'form': formulario,
            'operation': "Editar",
            'orden': orden
        }

        return render(request, self.template_name, contexto)


class OrdenTrabajoAPI(viewsets.ModelViewSet):
    queryset = OrdenTrabajo.objects.all()
    serializer_class = OrdenTrabajoSerializer
    pagination_class = GenericPagination
    filter_backends = (DjangoFilterBackend,)
    filter_class = OrdenTrabajoFilter


class OrdenTrabajoLastAPI(viewsets.ModelViewSet):
    queryset = OrdenTrabajo.objects.order_by('created_date')[:10]
    serializer_class = OrdenTrabajoSerializer


# ----------------- ACTIVIDAD ----------------- #

class ActividadListView(View):

    def __init__(self):
        self.template_name = 'actividad/lista.html'

    def get(self, _request, pk):

        orden = get_object_or_404(OrdenTrabajo, pk=pk)

        formulario = OrdenTrabajoForm(
            initial={
                'equipo': orden.equipo,
                'descripcion': orden.descripcion,
                'tipo': orden.tipo,
                'estado': orden.estado,
            }
        )

        formulario.fields['equipo'].widget.attrs['disabled'] = True
        formulario.fields['descripcion'].widget.attrs['disabled'] = True
        formulario.fields['tipo'].widget.attrs['disabled'] = True
        formulario.fields['estado'].widget.attrs['disabled'] = True

        contexto = {
            'form': formulario,
            'orden': orden
        }

        return render(_request, self.template_name, contexto)


class ActividadAPI(viewsets.ModelViewSet):
    queryset = Actividad.objects.all()
    serializer_class = ActividadSerializer

    filter_backends = (DjangoFilterBackend,)
    filter_fields = ('orden', 'id')


# ----------------- MANO OBRA ----------------- #

class ManoObraListView(View):

    def __init__(self):
        self.template_name = 'mano_obra/lista.html'

    def get(self, _request, pk):

        orden = get_object_or_404(OrdenTrabajo, pk=pk)

        formulario = OrdenTrabajoForm(
            initial={
                'equipo': orden.equipo,
                'descripcion': orden.descripcion,
                'tipo': orden.tipo,
                'estado': orden.estado,
            }
        )

        formulario.fields['equipo'].widget.attrs['disabled'] = True
        formulario.fields['descripcion'].widget.attrs['disabled'] = True
        formulario.fields['tipo'].widget.attrs['disabled'] = True
        formulario.fields['estado'].widget.attrs['disabled'] = True

        contexto = {
            'form': formulario,
            'orden': orden
        }

        return render(_request, self.template_name, contexto)


class ManoObraAPI(viewsets.ModelViewSet):
    queryset = ManoObra.objects.all()
    serializer_class = ManoObraSerializer

    filter_backends = (DjangoFilterBackend,)
    filter_fields = ('orden', 'id')


# ----------------- MATERIAL ----------------- #

class MaterialListView(View):

    def __init__(self):
        self.template_name = 'material/lista.html'

    def get(self, _request, pk):

        orden = get_object_or_404(OrdenTrabajo, pk=pk)

        formulario = OrdenTrabajoForm(
            initial={
                'equipo': orden.equipo,
                'descripcion': orden.descripcion,
                'tipo': orden.tipo,
                'estado': orden.estado,
            }
        )

        formulario.fields['equipo'].widget.attrs['disabled'] = True
        formulario.fields['descripcion'].widget.attrs['disabled'] = True
        formulario.fields['tipo'].widget.attrs['disabled'] = True
        formulario.fields['estado'].widget.attrs['disabled'] = True

        contexto = {
            'form': formulario,
            'orden': orden
        }

        return render(_request, self.template_name, contexto)


class MaterialAPI(viewsets.ModelViewSet):
    queryset = Material.objects.all()
    serializer_class = MaterialSerializer

    filter_backends = (DjangoFilterBackend,)
    filter_fields = ('orden', 'id')

trabajos/templates/actividad/lista.html
{% extends 'master.html' %}

{% load static from staticfiles %}

{% block title %} Actividades de Orden de Trabajo {% endblock title %}

{% block css %}

<!-- Kendo -->
<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.rtl.min.css' %}"/>
<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.common-bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.bootstrap.min.css' %}"/>

<!-- CoreM -->
<link rel="stylesheet" href="{% static 'grid.css' %}"/>


{% endblock css %}	


{% block contenido %}

	<!-- Content Header (Page header) -->
	<section class="content-header">
	  <h1>
	    <span id="titulo">Ordenes de Trabajo</span>
	    <small>Actividades</small>
	  </h1>
	  <ol class="breadcrumb">
	    <li><a href="{% url 'dashboards:inicio' %}"><i class="fa fa-home"></i>Inicio</a></li>
	    <li><a href="{% url 'trabajos:ordenes_lista' %}">Ordenes</a></li>
	    <li class="active">Actividades</li>
	  </ol>
	</section>

	<!-- Main content -->
	<section class="content" id="contenido">

		<div class="row">
			<form role="form" action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

				<div class="col-md-12">
					
					<div class="nav-tabs-custom">
						<ul class="nav nav-tabs pull-right">						
							<li><a id="tab_servicios" href="{% url 'trabajos:servicio_externo_lista' orden.id %}">Servicios</a></li>
							<li><a id="tab_mano_obra" href="{% url 'trabajos:mano_obra_lista' orden.id %}">Mano Obra</a></li>
							<li><a id="tab_materiales" href="{% url 'trabajos:material_lista' orden.id %}">Materiales</a></li>
							<li class="active">
								<a id="tab_actividades" href="#">Actividades</a>
							</li>
							<li><a href="{% url 'trabajos:ordenes_editar' orden.id %}">Generales</a></li>
<!-- 							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">
									Reportes 
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu">
									<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Imprimir OT</a></li>
									<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Imprimir Reporte de Mantenimiento</a></li>
								</ul>
							</li>	 -->					
							<li class="pull-left header"><i class="fa fa-th"></i> No. Orden: <strong id="ot_clave">{{ orden.id }}</strong> - <strong>{{ orden.descripcion }}</strong></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active">


								<div class="box box-info">
									<div class="box-header box-header-border">
										<h3 class="box-title">Registros</h3>
										<div class="box-tools pull-right">

											<a href="#win_modal" class="btn bg-purple btn-sm" data-toggle="modal" id="boton_nuevo">
												<i class="fa fa-plus-circle"></i>
												Nuevo
											</a>

											<button type="button" id="boton_exportar" class="btn bg-olive btn-sm">
											<i class="fa fa-file-excel-o"></i>
											Exportar
											</button>
										</div>
									</div>
									<div id="grid_principal">
									</div>
								</div>	


							</div>
							<!-- /.tab-pane -->
						</div> <!-- /.tab-content -->
							
					</div> <!-- nav-tabs-custom -->
				</div>

			</form>
		</div>

		<!-- win_modal -->
		<div class="modal fade" tabindex="-1" role="dialog" id="win_modal">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title"></h4>
		      </div>
		      <div class="modal-body">
					<div class="row">

						<input class="hidden" id="id_actividad" type="text" />

						<!-- Nombre -->
						<div class="col-sm-4">
							<div class="form-group has-warning" id="act_numero_contenedor">
								<label for="act_numero">
									<i class="fa  fa-asterisk  "></i>
									Numero:
								</label>
								<input class="form-control input-sm" id="act_numero" maxlength="144" type="number" />
								<span class="help-block hidden" id="act_numero_mensaje">Este campo es requerido.</span>
							</div>
						</div>

						<!-- Descripcion -->
						<div class="col-sm-8">
							<div class="form-group has-warning" id="act_desc_contenedor">
								<label for="act_desc">
									<i class="fa fa-asterisk"></i>
									Descripcion:
								</label>
								<input class="form-control input-sm" id="act_desc" maxlength="144" type="text" />
								<span class="help-block hidden" id="act_desc_mensaje">Este campo es requerido.</span>
							</div>
						</div>						
					</div>
			
					<div class="row">

						<!-- Horas Estimadas -->
						<div class="col-sm-6">
							<div class="form-group has-warning" id="act_hrs_est_contenedor">
								<label for="act_hrs_est">
									<i class="fa fa-asterisk"></i>
									Horas Estimadas:
								</label>
								<input class="form-control input-sm" id="act_hrs_est" maxlength="144" type="number" />
								<span class="help-block hidden" id="act_hrs_est_mensaje">Este campo es requerido.</span>
							</div>
						</div>

						<!-- Horas Reales -->
						<div class="col-sm-6">
							<div class="form-group" id="act_hrs_real_contenedor">
								<label for="act_hrs_real">
									Horas Reales:
								</label>
								<input class="form-control input-sm" id="act_hrs_real" maxlength="144" type="number" />
								<span class="help-block hidden" id="act_hrs_real_mensaje">Este campo es requerido.</span>
							</div>
						</div>	
					</div>

		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">
		        	<i class="fa fa-close"></i>
		        	Cerrar
		        </button>
		        <button type="button" class="btn btn-success" id="btn_modal_save">
		        	<i class="fa fa-save"></i>
		        	Guardar
		        </button>
		      </div>
		    </div><!-- /.modal-content -->
		  </div><!-- /.modal-dialog -->
		</div><!-- /.modal -->
	</section>
	<!-- /. Main content -->

{% endblock contenido %}

{% block scripts %}

	<!-- Kendo Js -->
	<script src="{% static 'libs/plugins/kendo_2015_2_624/js/cultures/kendo.culture.es-MX.min.js' %}"></script>
	<script src="{% static 'libs/plugins/kendo_2015_2_624/js/kendo.web.min.js' %}"></script>


	<!-- CoreM -->
	<script src="{% static 'actividad/lista.js' %}"></script>

{% endblock scripts %}