activos/urls.py
# -*- coding: utf-8 -*-

# Librerias Django:
from django.conf.urls import url

# Vistas:
from .views import EquipoListView
from .views import EquipoCreateView
from .views import EquipoUpdateView
from .views import EquipoTreeListView
from .views import EquipoHistory
from .views import EquipoTreeAPI

from .views import OdometroListView
from .views import OdometroCreateView
from .views import OdometroUpdateView

from .views import AnexoTextoView
from .views import AnexoImagenView
from .views import AnexoArchivoView

from .views import UbicacionCreateView
from .views import UbicacionListView
from .views import UbicacionUpdateView

from .views import UdmOdometroCreateView
from .views import UdmOdometroListView
from .views import UdmOdometroUpdateView

from .views import MedicionOdometroView


app_name = "activos"

urlpatterns = [

    # ----------------- EQUIPO ----------------- #
    url(
        r'^equipos/$',
        EquipoListView.as_view(),
        name='equipos_lista'
    ),
    url(
        r'^equipos/nuevo/$',
        EquipoCreateView.as_view(),
        name='equipos_nuevo'
    ),
    url(
        r'^equipos/editar/(?P<pk>.*)/$',
        EquipoUpdateView.as_view(),
        name='equipos_editar'
    ),
    url(
        r'equipos/arbol/(?P<pk>\d+)/$',
        EquipoTreeListView.as_view(),
        name='equipos_arbol'
    ),
    url(
        r'^equipos/arbol/json/(?P<pk>\d+)/$',
        EquipoTreeAPI.as_view(),
        name='equipos_api_tree'
    ),
    url(
        r'^equipos/historia/(?P<pk>.*)/$',
        EquipoHistory.as_view(),
        name='equipos_historia'
    ),

    # ----------------- ANEXOS ------------------ #

    url(
        r'equipos/anexos/(?P<pk>\d+)/texto/$',
        AnexoTextoView.as_view(),
        name='anexar_texto'
    ),
    url(
        r'^equipos/anexos/(?P<pk>\d+)/imagen/$',
        AnexoImagenView.as_view(),
        name='anexar_imagen'
    ),
    url(
        r'^equipos/anexos/(?P<pk>\d+)/archivo/$',
        AnexoArchivoView.as_view(),
        name='anexar_archivo'
    ),

    # ----------------- UBICACION ----------------- #

    url(
        r'ubicaciones/$',
        UbicacionListView.as_view(),
        name='ubicaciones_lista'
    ),
    url(
        r'^ubicaciones/nuevo/$',
        UbicacionCreateView.as_view(),
        name='ubicaciones_nuevo'
    ),
    url(
        r'^ubicaciones/editar/(?P<pk>\d+)/$',
        UbicacionUpdateView.as_view(),
        name='ubicaciones_editar'
    ),


    # ----------------- UDM ODOMETRO ----------------- #

    url(
        r'udmodometro/$',
        UdmOdometroListView.as_view(),
        name='udms_odometro_lista'
    ),
    url(
        r'udmodometro/nuevo/$',
        UdmOdometroCreateView.as_view(),
        name='udms_odometro_nuevo'
    ),
    url(
        r'udmodometro/editar/(?P<pk>\d+)/$',
        UdmOdometroUpdateView.as_view(),
        name='udms_odometro_editar'
    ),

    # ----------------- ODOMETRO ----------------- #
    url(
        r'^odometros/$',
        OdometroListView.as_view(),
        name='odometros_lista'
    ),
    url(
        r'^odometros/nuevo/$',
        OdometroCreateView.as_view(),
        name='odometros_nuevo'
    ),
    url(
        r'^odometros/editar/(?P<pk>.*)/$',
        OdometroUpdateView.as_view(),
        name='odometros_lista'
    ),

    # ----------------- MEDICION ----------------- #

    url(
        r'^odometros/(?P<pk>.*)/mediciones/$',
        MedicionOdometroView.as_view(),
        name='odometros_mediciones'
    ),

]

dashboards/urls.py
# -*- coding: utf-8 -*-

# Librerias Django:

# Urls
from django.conf.urls import url

# Vistas
from .views import Inicio

app_name = "dashboards"

urlpatterns = [

    url(
        r'^inicio/$',
        Inicio.as_view(),
        name='inicio'
    ),
]

home/urls.py
# -*- coding: utf-8 -*-

# Librerias django:
# from django.conf.urls import url

# Vistas:
# from .views import Index

# urlpatterns = [
#     url(r'^index/$', Index.as_view(), name='home.index'),
# ]

activos/views.py
# -*- coding: utf-8 -*-

# Django Atajos:
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

# Django Urls:
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse

# Django Generic Views
from django.views.generic.base import View
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import TemplateView

# Modelos:
from .models import Equipo
from .models import Odometro
from .models import Ubicacion
from .models import Medicion
from .models import UdmOdometro
from home.models import AnexoImagen
from home.models import AnexoArchivo
from home.models import AnexoTexto

# Formularios:
from .forms import EquipoFiltersForm
from .forms import EquipoForm
from .forms import UbicacionForm
from .forms import OdometroForm
from .forms import OdometroFiltersForm
from .forms import MedicionFiltersForm
from .forms import MedicionForm
from .forms import UdmOdometroForm
from home.forms import AnexoTextoForm
from home.forms import AnexoImagenForm
from home.forms import AnexoArchivoForm

# API Rest:
from rest_framework import viewsets
from rest_framework import filters
from django_filters.rest_framework import DjangoFilterBackend


# API Rest - Serializadores:
from .serializers import EquipoSerializer
from .serializers import EquipoTreeSerilizado
from .serializers import UbicacionSerializer
from .serializers import OdometroSerializer
from .serializers import MedicionSerializer
from .serializers import UdmOdometroSerializer
from home.serializers import AnexoTextoSerializer
from home.serializers import AnexoArchivoSerializer
from home.serializers import AnexoImagenSerializer

# API Rest - Paginacion:
from .pagination import GenericPagination

# API Rest - Filtros:
from .filters import EquipoFilter
from .filters import OdometroFilter
from .filters import MedicionFilter


# ----------------- EQUIPO ----------------- #

class EquipoListView(View):

    def __init__(self):
        self.template_name = 'equipo/lista.html'

    def get(self, request):

        formulario = EquipoFiltersForm()

        contexto = {
            'form': formulario
        }

        return render(request, self.template_name, contexto)


class EquipoCreateView(View):

    def __init__(self):
        self.template_name = 'equipo/formulario.html'

    def obtener_UrlImagen(self, _imagen):
        imagen = ''

        if _imagen:
            imagen = _imagen.url

        return imagen

    def get(self, request):
        formulario = EquipoForm()
        contexto = {
            'form': formulario,
            'operation': "Nuevo"
        }

        return render(request, self.template_name, contexto)

    def post(self, request):

        formulario = EquipoForm(request.POST, request.FILES)

        if formulario.is_valid():

            datos_formulario = formulario.cleaned_data
            equipo = Equipo()
            equipo.tag = datos_formulario.get('tag')
            equipo.descripcion = datos_formulario.get('descripcion')
            equipo.serie = datos_formulario.get('serie')
            equipo.tipo = datos_formulario.get('tipo')
            equipo.estado = datos_formulario.get('estado')
            equipo.padre = datos_formulario.get('padre')
            equipo.empresa = datos_formulario.get('empresa')
            equipo.sistema = datos_formulario.get('sistema')
            equipo.ubicacion = datos_formulario.get('ubicacion')
            equipo.imagen = datos_formulario.get('imagen')

            equipo.save()

            return redirect(
                reverse('activos:equipos_lista')
            )

        contexto = {
            'form': formulario,
            'imagen': self.obtener_UrlImagen(equipo.imagen),
            'operation': "Nuevo"
        }
        return render(request, self.template_name, contexto)


class EquipoUpdateView(View):

    def __init__(self):
        self.template_name = 'equipo/formulario.html'
        self.tag = ''

    def obtener_UrlImagen(self, _imagen):
        imagen = ''

        if _imagen:
            imagen = _imagen.url

        return imagen

    def get(self, request, pk):

        equipo = get_object_or_404(Equipo, pk=pk)
        self.tag = equipo.tag

        formulario = EquipoForm(
            instance=equipo
        )

        contexto = {
            'form': formulario,
            'tag': self.tag,
            'operation': "Editar",
            'equipo_id': equipo.id,
            'imagen': self.obtener_UrlImagen(equipo.imagen)
        }

        return render(request, self.template_name, contexto)

    def post(self, request, pk):

        equipo = get_object_or_404(Equipo, pk=pk)
        self.tag = equipo.tag

        formulario = EquipoForm(request.POST, request.FILES, instance=equipo)

        if formulario.is_valid():

            equipo = formulario.save(commit=False)
            equipo.save()

            return redirect(
                reverse('activos:equipos_lista')
            )

        contexto = {
            'form': formulario,
            'tag': self.tag,
            'operation': "Editar",
            'equipo_id': equipo.id,
            'imagen': self.obtener_UrlImagen(equipo.imagen)
        }
        return render(request, self.template_name, contexto)


class EquipoAPI(viewsets.ModelViewSet):
    queryset = Equipo.objects.all().order_by("-created_date")
    serializer_class = EquipoSerializer
    pagination_class = GenericPagination

    filter_backends = (DjangoFilterBackend,)
    filter_class = EquipoFilter


class EquipoTreeListView(View):

    def __init__(self):
        self.template_name = "equipo/arbol.html"

    def get(self, request, pk):

        equipo = get_object_or_404(Equipo, pk=pk)

        contexto = {
            "equipo": equipo
        }

        return render(request, self.template_name, contexto)


class EquipoTreeAPI(View):

    def get(self, request, pk):

        daddies = Equipo.objects.filter(pk=pk)

        serializador = EquipoTreeSerilizado()
        lista_json = serializador.get_Json(daddies)

        return HttpResponse(
            lista_json,
            content_type="application/json"
        )


class EquipoHistory(View):

    def __init__(self):
        self.template_name = 'equipo/historia.html'

    def get(self, request, pk):

        registros = Equipo.history.filter(id=pk).order_by("history_date")

        contexto = {
            'operation': "Historia",
            'equipo_id': pk,
            'registros': registros
        }

        return render(request, self.template_name, contexto)


# ----------------- EQUIPO - ANEXO ----------------- #

class AnexoTextoView(View):

    def __init__(self):
        self.template_name = 'equipo/anexos/anexos_texto.html'

    def get(self, request, pk):
        id_equipo = pk
        anexos = AnexoTexto.objects.filter(equipo=id_equipo)
        equipo = Equipo.objects.get(id=id_equipo)
        form = AnexoTextoForm()

        contexto = {
            'form': form,
            'id': id_equipo,
            'equipo': equipo,
            'anexos': anexos,
        }

        return render(request, self.template_name, contexto)

    def post(self, request, pk):
        id_equipo = pk
        form = AnexoTextoForm(request.POST)
        anexos = AnexoTexto.objects.filter(equipo=id_equipo)
        equipo = Equipo.objects.get(id=id_equipo)

        if form.is_valid():
            texto = form.save(commit=False)
            texto.equipo_id = id_equipo
            texto.save()
            anexos = AnexoTexto.objects.filter(equipo=id_equipo)
            form = AnexoTextoForm()
        return render(request, 'equipo/anexos/anexos_texto.html',
                      {'form': form, 'id': id_equipo, 'anexos': anexos,
                       'equipo': equipo})


class AnexoImagenView(View):

    def __init__(self):
        self.template_name = 'equipo/anexos/anexos_imagen.html'

    def get(self, request, pk):
        id_equipo = pk
        anexos = AnexoImagen.objects.filter(equipo=id_equipo)
        equipo = Equipo.objects.get(id=id_equipo)
        form = AnexoImagenForm()

        contexto = {
            'form': form,
            'id': id_equipo,
            'equipo': equipo,
            'anexos': anexos,
        }

        return render(request, self.template_name, contexto)

    def post(self, request, pk):
        id_equipo = pk
        anexos = AnexoImagen.objects.filter(equipo=id_equipo)
        equipo = Equipo.objects.get(id=id_equipo)
        form = AnexoImagenForm(request.POST, request.FILES)

        if form.is_valid():

            imagen_anexo = AnexoImagen()
            imagen_anexo.descripcion = request.POST['descripcion']
            if 'ruta' in request.POST:
                imagen_anexo.ruta = request.POST['ruta']
            else:
                imagen_anexo.ruta = request.FILES['ruta']
            imagen_anexo.equipo_id = id_equipo
            imagen_anexo.save()
            form = AnexoImagenForm()
            anexos = AnexoImagen.objects.filter(equipo=id_equipo)
            # return render(request, self.template_name,
            #               {'form': form, 'id': id_equipo, 'anexos': anexos,
            #                'equipo': equipo})
        contexto = {
            'form': form,
            'id': id_equipo,
            'equipo': equipo,
            'anexos': anexos,
        }
        return render(request, self.template_name, contexto)


class AnexoArchivoView(View):

    def __init__(self):
        self.template_name = 'equipo/anexos/anexos_archivo.html'

    def get(self, request, pk):
        id_equipo = pk
        anexos = AnexoArchivo.objects.filter(equipo=id_equipo)
        equipo = Equipo.objects.get(id=id_equipo)
        form = AnexoArchivoForm()

        contexto = {
            'form': form,
            'id': id_equipo,
            'equipo': equipo,

activos/templates/odometro/formulario.html
{% extends 'master.html' %}

{% load static from staticfiles %}

{% block title %} {{ operation }} Odómetros {% endblock title %}

{% block css %}

	<!-- Select2 -->
	<link rel="stylesheet" href="{% static 'libs/plugins/select2/select2.min.css' %}"/>

{% endblock %}

{% block contenido %}

<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
	<span id="titulo">Odómetros</span>
	<small>{{ operation }}</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="{% url 'dashboards:inicio' %}"><i class="fa fa-home"></i> Inicio</a></li>
		<li><a href="{% url 'activos:equipos_lista' %}">Odometros</a></li>
		<li class="active"> {{ operation }}</li>
	</ol>
</section>

<!-- Main content -->
<section class="content" id="contenido">
	<div class="row">
		<div class="col-md-12">
			<!-- Filtros -->
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Favor de proporcionar los siguientes datos:</h3>
				</div>
				<!-- /.box-header -->
				<form role="form" action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
					<div class="box-body">


						<!-- Clave y Descripcion -->
						<div class="row">
							<div class="col-sm-4">

								<div class="form-group {% if form.clave.field.required %} has-warning {% endif %} {% if form.clave.errors %} has-error {% endif %}">

								  	<label class="control-label">
								  		<i class="fa {% if form.clave.field.required %} fa-asterisk {% endif %} {% if form.clave.errors %} fa-asterisk {% endif %}"></i> 
								  		{{ form.clave.label }} 
								 	</label>
								    {{ form.clave }}
								  
								    {% for error in form.clave.errors %}
								    <span class="help-block">{{ error }}</span>
								    {% endfor %}
								</div>
							</div>

							<div class="col-sm-8">

								<div class="form-group {% if form.descripcion.field.required %} has-warning {% endif %} {% if form.descripcion.errors %} has-error {% endif %}">

								  	<label class="control-label">
								  		<i class="fa {% if form.descripcion.field.required %} fa-asterisk {% endif %} {% if form.descripcion.errors %} fa-asterisk {% endif %}"></i> 
								  		{{ form.descripcion.label }} 
								 	</label>
								    {{ form.descripcion }}
								  
								    {% for error in form.descripcion.errors %}
								    <span class="help-block">{{ error }}</span>
								    {% endfor %}
								</div>
							</div>	
						</div>	

						<!-- Equipo, UDM y Activo -->
						<div class="row">
							<div class="col-sm-6">

								<div class="form-group {% if form.equipo.field.required %} has-warning {% endif %} {% if form.equipo.errors %} has-error {% endif %}">

								  	<label class="control-label">
								  		<i class="fa {% if form.equipo.field.required %} fa-asterisk {% endif %} {% if form.equipo.errors %} fa-asterisk {% endif %}"></i> 
								  		{{ form.equipo.label }} 
								 	</label>
								    {{ form.equipo }}
								  
								    {% for error in form.equipo.errors %}
								    <span class="help-block">{{ error }}</span>
								    {% endfor %}
								</div>
							</div>

							<div class="col-sm-6">

								<div class="form-group {% if form.udm.field.required %} has-warning {% endif %} {% if form.udm.errors %} has-error {% endif %}">

								  	<label class="control-label">
								  		<i class="fa {% if form.udm.field.required %} fa-asterisk {% endif %} {% if form.udm.errors %} fa-asterisk {% endif %}"></i> 
								  		{{ form.udm.label }} 
								 	</label>
								    
									<div class="input-group input-group-sm">
										{{ form.udm }}
									  	<div class="input-group-btn input_icons">
											<a href="#win_udm" class="btn btn-default btn-sm" data-toggle="modal" id="btn_edit_udm">
												<i class="glyphicon glyphicon-pencil"></i>
											</a>
											<a href="#win_udm" class="btn btn-default btn-sm" data-toggle="modal" id="btn_new_udm">
												<i class="glyphicon glyphicon-plus-sign"></i>
											</a>
										</div>
									</div>
								  
								    {% for error in form.udm.errors %}
								    <span class="help-block">{{ error }}</span>
								    {% endfor %}
								</div>
							</div>
						</div>	

						<div class="row">
							
							<div class="col-sm-12">

								<div class="form-group {% if form.esta_activo.field.required %} has-warning {% endif %} {% if form.esta_activo.errors %} has-error {% endif %}">

								  	<label class="control-label">
								  		<i class="fa {% if form.esta_activo.field.required %} fa-asterisk {% endif %} {% if form.esta_activo.errors %} fa-asterisk {% endif %}"></i> 
								  		<div>{{ form.esta_activo.label }} </div>
								 	</label>
								    {{ form.esta_activo }}
								  
								    {% for error in form.esta_activo.errors %}
								    <span class="help-block">{{ error }}</span>
								    {% endfor %}
								</div>

							</div>							
						</div>

					</div>
					<!-- /.box-body -->

					<div class="box-footer">
						<a class="btn btn-default" href="{% url 'activos:odometros_lista' %}">
							<i class="fa fa-arrow-circle-left"></i>
							Regresar
						</a>
						<button type="submit" class="btn btn-success pull-right">
							<i class="fa fa-save"></i>
							Guardar
						</button>
					</div>
					<!-- /.box-footer -->
				</form>
			</div>
			<!-- /.box -->
		</div>
	</div>

	<!-- PopUp -->
	<div class="modal fade" tabindex="-1" role="dialog" id="win_udm">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title"></h4>
	      </div>
	      <div class="modal-body">

				<input class="hidden" id="udm_id" type="text" />

				<div class="row">
					<div class="col-sm-10 col-md-offset-1">
						<div class="form-group has-warning" id="udm_clave_contenedor">
							<label for="udm_clave">
								<i class="fa  fa-asterisk  "></i>
								Clave:
							</label>
							<input class="form-control" id="udm_clave" maxlength="144" type="text" />
							<span class="help-block hidden" id="udm_clave_mensaje">Este campo es requerido.</span>
						</div>
					</div>
				</div>
		
				<div class="row">
					<div class="col-sm-10 col-md-offset-1">
						<div class="form-group has-warning" id="udm_desc_contenedor">
							<label for="udm_descripcion">
								<i class="fa fa-asterisk"></i>
								Descripcion:
							</label>
							<input class="form-control" id="udm_descripcion" maxlength="144" type="text" />
							<span class="help-block hidden" id="udm_desc_mensaje">Este campo es requerido.</span>
						</div>
					</div>
				</div>

	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">
	        	<i class="fa fa-close"></i>
	        	Cerrar
	        </button>
	        <button type="button" class="btn btn-success" id="bnt_udm-save">
	        	<i class="fa fa-save"></i>
	        	Guardar
	        </button>
	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->


</section>
<!-- /. Main content -->
{% endblock contenido %}

{% block scripts %}

<!-- Select2 -->
<script src="{% static 'libs/plugins/select2/select2.full.min.js' %}"></script>

<!-- CoreM -->
<script src="{% static 'odometro/formulario.js' %}"></script>

{% endblock %}

activos/templates/odometro/lista.html
{% extends 'master.html' %}

{% load static from staticfiles %}

{% block title %} CoreM - Odómetros {% endblock title %}

{% block css %}

<!-- Kendo -->
<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.rtl.min.css' %}"/>
<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.common-bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'libs/plugins/kendo_2015_2_624/styles/kendo.bootstrap.min.css' %}"/>

<!-- Select2 -->
<link rel="stylesheet" href="{% static 'libs/plugins/select2/select2.min.css' %}"/>

<!-- Pace -->
<link rel="stylesheet" href="{% static 'libs/plugins/pace/pace.min.css' %}"/>

<!-- CoreM -->
<link rel="stylesheet" href="{% static 'grid.css' %}"/>

{% endblock css %}

{% block contenido %}
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
	<span id="titulo">Odómetros</span>
	<small>Consulta</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="{% url 'dashboards:inicio' %}"><i class="fa fa-home"></i> Inicio</a></li>
		<li class="active">Odómetros</li>
	</ol>
</section>
<!-- Main content -->
<section class="content" id="contenido">
	<div class="row">
		<div class="col-md-12">
			<!-- Filtros -->
			<div class="box box-solid box-info" id="id_panel">
				<div class="box-header with-border">
					<h3 class="box-title">Filtros</h3>
					<div class="box-tools pull-right">
						<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
					</div>
				</div>
				<!-- /.box-header -->
				<form role="form" action=""> {% csrf_token %}
					<div class="box-body">
						<div class="row">
							<div class="form-group col-sx-12 col-sm-4 col-md-4">
								<label for="{{ form.equipo.id_for_label }}">Equipo</label>
								{{ form.equipo }}
							</div>
							<div class="form-group col-sx-12 col-sm-4 col-md-4">
								<label for="{{ form.clave.id_for_label }}">Clave</label>
								{{ form.clave }}
							</div>
							<div class="form-group col-sx-12 col-sm-4 col-md-4">
								<label for="{{ form.udm.id_for_label }}">UDM</label>
								{{ form.udm }}
							</div>
						</div>
						<div class="row">
							<div class="form-group col-sx-12 col-sm-12 col-md-12">
								<label for="{{ form.descripcion.id_for_label }}">Descripción</label>
								{{ form.descripcion }}
							</div>
						</div>
					</div>
					<!-- /.box-body -->
					<div class="box-footer">
						<button type="submit" id="boton_limpiar" class="btn btn-default">
							<i class="fa fa-eraser"></i>
							Limpiar
						</button>
						<button type="submit" id="boton_buscar" class="btn btn-info pull-right">
							<i class="fa fa-search"></i>
							Buscar
						</button>
					</div>
					<!-- /.box-footer -->
				</form>
			</div>
			<!-- /.box -->
		</div>
	</div>
	<div class="box box-info">
		<div class="box-header box-header-border">
			<h3 class="box-title">Registros</h3>
			<div class="box-tools pull-right">
				<button type="button" id="boton_nuevo" class="btn bg-purple btn-sm">
				<i class="fa fa-plus-circle"></i>
				Nuevo
				</button>
				<button type="button" id="boton_exportar" class="btn bg-olive btn-sm">
				<i class="fa fa-file-excel-o"></i>
				Exportar
				</button>
			</div>
		</div>
		<div id="grid_principal">
		</div>
	</div>
	<!-- /.box -->
</section>
<!-- /. Main content -->

{% endblock contenido %}

{% block scripts %}

<!-- Kendo Js -->
<script src="{% static 'libs/plugins/kendo_2015_2_624/js/cultures/kendo.culture.es-MX.min.js' %}"></script>
<script src="{% static 'libs/plugins/kendo_2015_2_624/js/kendo.web.min.js' %}"></script>

<!-- Select2 -->
<script src="{% static 'libs/plugins/select2/select2.full.min.js' %}"></script>

<!-- Pace -->
<script src="{% static 'libs/plugins/pace/pace.min.js' %}"></script>

<!-- CoreM -->
<script src="{% static 'odometro/lista.js' %}"></script>

{% endblock scripts %}